export default {
    widgets:[
        {
            label:'Чайник',
            description:'Чайник на кухне',
            class:'default',
            config:{
                sensors:[
                    {
                        view:'main',
                        title:'Temperature',
                        sensor:'device1.sensor1'                        
                    },
                    {
                        view:'main',
                        title:'Level',
                        sensor:'device1.sensor2'
                    },
                    {
                        view:'main',
                        title:'State',
                        sensor:'device1.state'
                    },
                    {
                        view:'main',
                        title:'Flags',
                        sensor:'device1.flagsensor'
                    }
                ]                                           
            }            
        },
        {
            label:'CUSTOM1',
            class:'custom'
        },        
        {
            label:'CUSTOM2',
            class:'custom'
        }
    ]
}